// page links
export const whatIsADigesu = "/"
export const aboutDigesu = "/about-digesu"
export const differenceBetweenDigesuAndOtherDapps =
  "/difference-between-digesu-and-other-apps"
export const whatIsABand = "/what-is-a-band"
export const stepsInABand = "/steps-in-a-band"
export const quorum = "/quorum"
export const amount = "/amount"
export const duration = "/duration"
export const multiplier = "/multiplier"
export const liquidation = "/liquidation"
export const publicVsPrivateBand = "/public-private-band"
export const cycle = "/cycle"
export const howToGetFinance = "/how-to-get-finance"
export const howToPayback = "/how-to-payback"
export const howToClaimDues = "/how-to-claim-dues"
export const testnetInfo = "/testnet-info" 
