// page links
export const flexPools = "/"
export const aboutFlexPool = "/about-flexpool"
export const differenceBetweenFlexPoolAndExistingLiquidityPools =
  "/difference-between-flexpool-and-existing-liquidity-pools"
export const whatIsAFlexPool = "/what-is-a-flexpool"
export const stepsInAFlexPool = "/steps-in-a-flexpool"
export const quorum = "/quorum"
export const amount = "/amount"
export const duration = "/duration"
export const multiplier = "/multiplier"
export const liquidation = "/liquidation"
export const permissionedVsPermissionlessPool = "/permissionless-permissioned-pool"
export const cycle = "/cycle"
export const howToGetFinance = "/how-to-get-finance"
export const howToPayback = "/how-to-payback"
export const howToWithdraw = "/how-to-withdraw"
export const testnetInfo = "/testnet-info" 
